[package]
name = "uv2nix"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
log = "0.4.21"
env_logger = "0.11.3"
clap = { version = "4.0", features = ["derive"] }
clap-verbosity-flag = "2.2.0"
tempfile = "3.12.0"
toml = "0.8.19"
serde = { version = "1.0", features = ["derive"] }
