[project]
name = "uv2nix"
version = "0.1.0"
description = "Example project"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "typer",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
